#code for the calculator's GUI
from tkinter import *
root = Tk()
root.geometry("1200x750")

#calculator as bg image 
bg = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Calculator.png")
label = Label(root, image = bg)
label.place(x = 0, y = 0)

#images for the buttons
image1x1 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x1 n (12x).png")
image1x2 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x2 i (12dif).png")
image1x3 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x3 PV (CFo).png")
image1x4 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x4 PMT (CFj).png")
image1x5 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x5 FV (Nj).png")
image1x6 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x6 CHS (DATE).png")
image1x7 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x7 7 (BEG).png")
image1x8 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x8 8 (END).png")
image1x9 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x9 9 (MEM).png")
image1x10 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\1x10 sym divide.png")
image2x1 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x1 Y^x (sqrt(X)).png")
image2x2 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x2 Recip(x) (e^x).png")
image2x3 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x3 Total% (LN).png")
image2x4 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x4 Delta% (FRAC).png")
image2x5 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x5 % (INTG).png")
image2x6 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x6 EEX (DeltaDays).png")
image2x7 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x7 4 (D.MY).png")
image2x8 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x8 5 (M.DY).png")
image2x9 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x9 6 (Xbar W).png")
image2x10 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\2x10 sym mul.png")
image3x1 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x1 Run-Stop (PSE).png")
image3x2 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x2 Single Step (BST).png")
image3x3 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x3 R Down (Go-to).png")
image3x4 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x4 X switch Y (X less_ Y).png")
image3x5 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x5 Clear (X=0).png")
image3x6 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x6 ENTER (LSTx).png")
image3x7 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x7 1 (Xconst r).png")
image3x8 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x8 2 (Yconst r).png")
image3x9 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x9 3 (n!).png")
image3x10 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\3x10 sym minus (del).png")
image4x1 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x1 ON.png")
image4x2 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x2 shift F.png")
image4x3 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x3 Shift G.png")
image4x4 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x4 Store.png")
image4x5 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x5 Recall.png")
image4x7 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x7 0 (Xbar).png")
image4x8 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x8 Decimal (S).png")
image4x9 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x9 Sum+ (Sum-).png")
image4x10 = PhotoImage(file = "C:\\Users\\Key\\Desktop\\PyProFE\\PyProjectFE\\Buttons\\4x10 sym plus.png")

#buttons for the calculator
button1x1 = Button(root, image = image1x1)
button1x1.place(x=73, y=257)
button1x2 = Button(root, image = image1x2)
button1x2.place(x=183, y=257)
button1x3 = Button(root, image = image1x3)
button1x3.place(x=290, y=257)
button1x4 = Button(root, image = image1x4)
button1x4.place(x=399, y=257)
button1x5 = Button(root, image = image1x5)
button1x5.place(x=505, y=257)
button1x6 = Button(root, image = image1x6)
button1x6.place(x=614, y=257)
button1x7 = Button(root, image = image1x7)
button1x7.place(x=721, y=257)
button1x8 = Button(root, image = image1x8)
button1x8.place(x=828, y=257)
button1x9 = Button(root, image = image1x9)
button1x9.place(x=936, y=257)
button1x10 = Button(root, image = image1x10)
button1x10.place(x=1044, y=257)
button2x1 = Button(root, image = image2x1)
button2x1.place(x=73, y=377)
button2x2 = Button(root, image = image2x2)
button2x2.place(x=183, y=377)
button2x3 = Button(root, image = image2x3)
button2x3.place(x=290, y=377)
button2x4 = Button(root, image = image2x4)
button2x4.place(x=399, y=377)
button2x5 = Button(root, image = image2x5)
button2x5.place(x=505, y=377)
button2x6 = Button(root, image = image2x6)
button2x6.place(x=614, y=377)
button2x7 = Button(root, image = image2x7)
button2x7.place(x=721, y=377)
button2x8 = Button(root, image = image2x8)
button2x8.place(x=828, y=377)
button2x9 = Button(root, image = image2x9)
button2x9.place(x=936, y=377)
button2x10 = Button(root, image = image2x10)
button2x10.place(x=1044, y=377)
button3x1 = Button(root, image = image3x1)
button3x1.place(x=73, y=497)
button3x2 = Button(root, image = image3x2)
button3x2.place(x=183, y=497)
button3x3 = Button(root, image = image3x3)
button3x3.place(x=290, y=497)
button3x4 = Button(root, image = image3x4)
button3x4.place(x=399, y=497)
button3x5 = Button(root, image = image3x5)
button3x5.place(x=505, y=497)
button3x6 = Button(root, image = image3x6)
button3x6.place(x=614, y=497)
button3x7 = Button(root, image = image3x7)
button3x7.place(x=721, y=497)
button3x8 = Button(root, image = image3x8)
button3x8.place(x=828, y=497)
button3x9 = Button(root, image = image3x9)
button3x9.place(x=936, y=497)
button3x10 = Button(root, image = image3x10)
button3x10.place(x=1044, y=497)
button4x1 = Button(root, image = image4x1)
button4x1.place(x=73, y=615)
button4x2 = Button(root, image = image4x2)
button4x2.place(x=183, y=615)
button4x3 = Button(root, image = image4x3)
button4x3.place(x=290, y=615)
button4x4 = Button(root, image = image4x4)
button4x4.place(x=399, y=615)
button4x5 = Button(root, image = image4x5)
button4x5.place(x=505, y=615)
button4x7 = Button(root, image = image4x7)
button4x7.place(x=721, y=615)
button4x8 = Button(root, image = image4x8)
button4x8.place(x=828, y=615)
button4x9 = Button(root, image = image4x9)
button4x9.place(x=936, y=615)
button4x10 = Button(root, image = image4x10)
button4x10.place(x=1044, y=615)

root.mainloop()

#26/11/22: attempt to program RPN for calculator
#def RPN():
#    stm = True
#    while stm:
#        list = []
#        try:
#            x = int(input())
#            list.append(x)
#        except:
#            stm = False
#        return list
#print(RPN())